### ISSUE TITLE
error installing 

### ISSUE THREAD

**Issue by dodi-alx-account** [PortSwigger/BChecks#51]
i have updated my burp pro to the latest version (v2023.6.2) and when try to install the plugin i get this error 
```
java.lang.Exception: Extension class is not a recognized type
	at burp.Zbmc.Zp(Unknown Source)
	at burp.Zbmc.Zo(Unknown Source)
	at burp.Zkfl.ZZ(Unknown Source)
	at burp.Zb5f.Zv(Unknown Source)
	at burp.Zb3r.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```
where is the problem here 
the java version is 19

**Comment by A-J-C** [comment]
What plugin are you trying to install? BChecks is a built in feature, you should be able to find it as a subtab underneath the extensions tab.

**Comment by dodi-alx-account** [comment]
sorry i tried to install the .jar file . i didn't see it on the extension tab
